version: "3.7"

services:
    php:
        image: thecodingmachine/php:8.1-v4-cli
        environment:
            - PHP_EXTENSION_XDEBUG=1
        init: true
        volumes:
            - $PWD:/usr/src/app
