version: "2"

services:
    composer:
        image: composer:latest
        entrypoint: composer
        volumes:
            - $PWD:/app
        working_dir: /app

    php:
        image: php:8.1-cli
        volumes:
            - $PWD:/app
        working_dir: /app
